# Description:
#   Why should I care what color the bikeshed is?
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot bikeshed

why = [
  "Why should I care what color the bikeshed is?",
]
response = [
  "The really, really short answer is that you should not.",
  "The somewhat longer answer is that just because you are capable of building a bikeshed does not mean you should stop others from building one just because you do not like the color they plan to paint it. This is a metaphor indicating that you need not argue about every little feature just because you know enough to do so. Some people have commented that the amount of noise generated by a change is inversely proportional to the complexity of the change."
]

module.exports = (robot) ->

  robot.respond /bikeshed/i, (msg) ->
    msg.send why
    msg.send msg.random response
